version: '3.9'
services:
  backend:
    container_name: backend
    image: oven/bun:latest
    working_dir: /app
    tty: true
    user: root
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    command: sh -c "bun dev"
    ports:
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - integration

  frontend:
    container_name: frontend
    image: node:18-alpine
    working_dir: /app
    tty: true
    user: root
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev --host"
    ports:
      - '5173:5173'
    expose:
      - '5173'
    networks:
      - integration
networks:
  integration:
    driver: bridge